name: Deploy frontend
#deploy frontend trigger

on:
  push:
    branches: 
     - 'main'
    paths: 
     - 'frontend/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
    deploy:
    name: DeployFrontEnd
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: DeployFrontEnd
      run: |-
        gsutil -m rsync -R frontend gs://$GCS_BUCKET