name: Deploy frontend
#deploy frontend trigger

on:
  push:
    branches: 
     - 'main'
    paths: 
     - 'frontend/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  GCP_LB: ${{ secrets.GCP_LB }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R frontend gs://$GCS_BUCKET
    
    - name: Invalidate
      run: |-
        gcloud compute url-maps invalidate-cdn-cache $GCP_LB --path "/*" --async